language: node_js
sudo: required
env:
  - MONGO_CONNECTION="mongodb://localhost/test_db" storageURI="mongodb://localhost/test_db"
node_js:
  - "8.1.4"
  - "8.4.0"
matrix:
  fast_finish: true
services:
  - mongodb
  - docker
script: make travis
after_success:
  - nvm version
  - if [[ ! -z "$DOCKER_USER" ]]; then docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && git checkout -- . && git clean -fd . && make docker_release; fi
after_script: make report
